// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyqmonnibecfnpunpxid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5cW1vbm5pYmVjZm5wdW5weGlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNzE1MzAsImV4cCI6MjA2NTk0NzUzMH0.bmyhjhbmew6gwHhBDeF8jZVBi8hgevAI5k5CnZOIR_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);